### ISSUE TITLE
Change the template engine to EJS

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Tracker#5]
Shall we use [EJS](www.embeddedjs.com)  as the template engine instead of Jade? 
Because EJS is much similar to plain old HTML and people with HTML knowledge can easily catch faster than Jade.

**Comment by tharindupr** [comment]
Good idea.

**Comment by milankarunarathne** [comment]
@agentmilindu @tharindupr I want to contribute into this issue, since I have previous experience in using both template engines. Seems to be it [already using EJS template engine](https://github.com/scorelab/Tracker/commit/c320640f03a9e5ba8efeb919aea5c91e86ed277b). I think, we can close this issue now :+1:

**Comment by agentmilindu** [comment]
Thanks @milankarunarathne for pointing out! :+1:
